# Generated by Django 4.1.1 on 2022-09-27 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('part_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('IS', 'In stock'), ('SD', 'Special delivery'), ('PA', 'Pending availability'), ('OS', 'Out of stock'), ('NA', 'Not available')], default='IS', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'item',
                'ordering': ['-title'],
            },
        ),
    ]
