# Generated by Django 4.1.1 on 2022-09-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_formats',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
